// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4dr_UkpDIAWdjD0o7CKJNYFSeMXau_X4',
    appId: '1:245277515121:web:a677f11a537035f88a6ad0',
    messagingSenderId: '245277515121',
    projectId: 'vpost-febb3',
    authDomain: 'vpost-febb3.firebaseapp.com',
    storageBucket: 'vpost-febb3.appspot.com',
    measurementId: 'G-K15DRLH9Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQyiEMAyTIwJ5VX-LcMsk7oUwmWoQjEWE',
    appId: '1:245277515121:android:c4e5d2940d4df7c18a6ad0',
    messagingSenderId: '245277515121',
    projectId: 'vpost-febb3',
    storageBucket: 'vpost-febb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAokaNIshLw5e9YtCcZbAu3DAeCbdPT30',
    appId: '1:245277515121:ios:a13c4ade89dc61aa8a6ad0',
    messagingSenderId: '245277515121',
    projectId: 'vpost-febb3',
    storageBucket: 'vpost-febb3.appspot.com',
    iosClientId: '245277515121-jib322pt6fuqdplh8ir64117t9ido4qk.apps.googleusercontent.com',
    iosBundleId: 'com.example.projects',
  );
}
